[package]
name = "redjaxk-podgate"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
redjaxk-protocol = { path = "../../libs/redjaxk-protocol" }
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
